#!/bin/bash

VERSION=0.1.0
IN=dist/backbone.viewmodel-$VERSION.js
OUT=dist/backbone.viewmodel-$VERSION.min.js

echo "Development: $IN"
echo "Production: $OUT"

cat backbone.viewmodel.js backbone.binding.js backbone.computed.js lib/bindings.js > $IN

curl -s \
        -d compilation_level=SIMPLE_OPTIMIZATIONS \
        -d output_format=text \
        -d output_info=compiled_code \
        --data-urlencode "js_code@${IN}" \
        http://closure-compiler.appspot.com/compile \
        > $OUT